package runners;

import java.util.List;
import java.util.Map;

import org.testng.TestNG;

import constants.ESignetConstants;
import io.mosip.testrig.apirig.testrunner.BaseTestCase;
import io.mosip.testrig.apirig.testrunner.ExtractResource;
import io.mosip.testrig.apirig.utils.AdminTestUtil;
import utils.EsignetConfigManager;
import utils.EsignetUtil;

/**
 * Standalone entry point that creates one real identity (POST
 * /idrepository/v1/identity/) and a Perpetual VID for it (POST
 * /idrepository/v1/vid), then prints every captured auto-generated id
 * (UIN, RID, EMAIL, PHONE, VID).
 *
 * Deliberately skips everything runners.Runner.main() normally does around
 * this: Keycloak test-user recreation, policy/partner provisioning, device
 * generation, and the full Cucumber UI run. None of that is needed for the
 * "idrepo" role token used by AddIdentity / CreateVID, so this only touches
 * the ID Repository — same environment config.properties already points at.
 *
 * Run (after `mvn compile`, from the ui-test module root):
 *
 *   mvn -q org.codehaus.mojo:exec-maven-plugin:3.1.0:java ^
 *       -Dexec.mainClass=runners.GenerateVidRunner ^
 *       -Dexec.classpathScope=test ^
 *       -Denv.endpoint=https://api-internal.qa11new.mosip.net ^
 *       -Denv.user=api-internal.qa11new ^
 *       -Denv.testLevel=smoke
 *
 * env.endpoint / env.user must match the idrepository entry under
 * mosip_components_base_urls in config.properties.
 */
public class GenerateVidRunner {

	public static String jarUrl = GenerateVidRunner.class.getProtectionDomain().getCodeSource().getLocation()
			.getPath();

	public static void main(String[] args) {
		String runType = getRunType();

		BaseTestCase.setRunContext(runType, jarUrl);
		ExtractResource.removeOldMosipTestTestResource();
		if (runType.equalsIgnoreCase("JAR")) {
			ExtractResource.extractCommonResourceFromJar();
		} else {
			ExtractResource.copyCommonResources();
		}

		AdminTestUtil.init();
		EsignetConfigManager.init();
		EsignetUtil.getPluginName();

		BaseTestCase.initialize();
		BaseTestCase.currentModule = ESignetConstants.ESIGNETUI_MODULENAME;
		BaseTestCase.certsForModule = ESignetConstants.ESIGNETUI_MODULENAME;
		AdminTestUtil.copymoduleSpecificAndConfigFile(ESignetConstants.ESIGNETUI_MODULENAME);
		AdminTestUtil.getRequiredField();

		TestNG runner = new TestNG();
		runner.setTestSuites(List.of("testNgXmlFiles/GenerateVidSuite.xml"));
		runner.setOutputDirectory("testng-report");
		runner.run();

		System.out.println("\n===== Generated auto IDs (includes UIN and VID) =====");
		for (Map.Entry<String, String> entry : AdminTestUtil.autoGeneratedIDValueCache.entrySet()) {
			System.out.println(entry.getKey() + " = " + entry.getValue());
		}
		System.out.println("======================================================\n");

		System.exit(runner.hasFailure() ? 1 : 0);
	}

	public static String getRunType() {
		if (GenerateVidRunner.class.getResource("GenerateVidRunner.class").getPath().contains(".jar"))
			return "JAR";
		else
			return "IDE";
	}
}
